name: CI

on:
    push:
        branches:
            - main
    merge_group:
        types: [checks_requested]
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - "*"
            - "!renovate/web"

jobs:
    validate:
        name: ${{ matrix.task.name }}
        timeout-minutes: 15
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task:
                    - name: Check Build
                      run: pnpm run ci
                    - name: Check Formatting
                      run: biome ci .
                    - name: Run Tests
                      run: pnpm run test

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Setup Biome
              if: ${{ matrix.task.run == 'biome ci .' }}
              uses: biomejs/setup-biome@v2

            - name: ${{ matrix.task.name }}
              run: ${{ matrix.task.run }}
              env:
                WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
